services:
  todoist:
    image: todoist
    container_name: todoist
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${TODOIST_PORT:-8000}:${TODOIST_PORT:-8000}"
    volumes:
      - ./todoist:/usr/local/todoist/todoist:ro # sync the source code and container code
    env_file:
      - ./.env
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - todoist-network

  postgres_db:
    image: "postgres:15.2"
    container_name: postgres_db
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER" ]
      interval: 10s
      retries: 10
      start_period: 5s
      timeout: 5s
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todoist-network

networks:
  todoist-network:
    name: todoist-network

volumes:
  postgres_data:
    name: postgres_data
